### ISSUE TITLE
0/1 Knapsack problem 

### ISSUE THREAD

**Issue by MAYURIKOTHARI299** [tuhinsunny/Algorithms_DSA_SSOC#2]
@tuhinsunny I would like to add this algorithm under SSoc 2.0. Please assign me this issue.

**Comment by tuhinsunny** [comment]
Yes Sure, am assigning

**Comment by tuhinsunny** [comment]
@MAYURIKOTHARI299 I have assigned you the issue  . Can you now contribute?

**Comment by tuhinsunny** [comment]
@MAYURIKOTHARI299 I have added the label . Now is it okay?

**Comment by MAYURIKOTHARI299** [comment]
@tuhinsunny you need to add this label in PR and not issue could you plz do that and also for all othar of PRs merged. Thankyou!!
